import array as arr
workingdirectory='C:/Users/adh37/OneDrive - Science and Technology Facilities Council/Data/Negative Muons/Experiments/Wallace Steel'
dataset_GE1 = arr.array('i',[])
dataset_GE2 = arr.array('i',[])
dataset_GE3 = arr.array('i',[])
dataset_GE4 = arr.array('i',[])
plot_GE1 = True
plot_GE2 = False
plot_GE3 = True
plot_GE4 = False
flag_d_GE1 = 0
flag_d_GE2 = 0
flag_d_GE3 = 0
flag_d_GE4 = 0
x_GE1 = arr.array('i', [])
y_GE1 = arr.array('i', [])
err_GE1 = arr.array('i', [])
x_GE2 = arr.array('i', [])
y_GE2 = arr.array('i', [])
err_GE2 = arr.array('i', [])
x_GE3 = arr.array('i', [])
y_GE3 = arr.array('i', [])
err_GE3 = arr.array('i', [])
x_GE4 = arr.array('i', [])
y_GE4 = arr.array('i', [])
err_GE4 = arr.array('i', [])
x_GE1_Ncounts = arr.array('i', [])
y_GE1_Ncounts = arr.array('i', [])
err_GE1_Ncounts = arr.array('i', [])
x_GE2_Ncounts = arr.array('i', [])
y_GE2_Ncounts = arr.array('i', [])
err_GE2_Ncounts = arr.array('i', [])
x_GE3_Ncounts = arr.array('i', [])
y_GE3_Ncounts = arr.array('i', [])
err_GE3_Ncounts = arr.array('i', [])
x_GE4_Ncounts = arr.array('i', [])
y_GE4_Ncounts = arr.array('i', [])
err_GE4_Ncounts = arr.array('i', [])
x_GE1_NEvents = arr.array('i', [])
y_GE1_NEvents = arr.array('i', [])
err_GE1_NEvents = arr.array('i', [])
x_GE2_NEvents = arr.array('i', [])
y_GE2_NEvents = arr.array('i', [])
err_GE2_NEvents = arr.array('i', [])
x_GE3_NEvents = arr.array('i', [])
y_GE3_NEvents = arr.array('i', [])
err_GE3_NEvents = arr.array('i', [])
x_GE4_NEvents = arr.array('i', [])
y_GE4_NEvents = arr.array('i', [])
err_GE4_NEvents = arr.array('i', [])



starttime_str = ''
endtime_str = ''
events_str = ''
comment_str = ''
RunNum = 0
peakdata = ''
peak_data = {}
Normalise_counts = True
Normalise_spill = False
Normalise_do_not = False